name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run check
        run: bun check
      - name: Run tests
        run: bun test
      - name: Build binaries
        run: bun build-cli
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          upload_url=$(gh api --method POST \
            /repos/mutongx/p4m/releases \
              -f tag_name="$GITHUB_REF_NAME" \
          | jq -r .upload_url)
          curl \
              -u "token:$GH_TOKEN" \
              -H "Content-Type: application/x-executable" \
              -T dist/p4m \
            "${upload_url%%{?*}?name=p4m"
        env:
          GH_TOKEN: ${{ github.token }}
